name = "akavango-proxy"
main = "index.js"
compatibility_date = "2024-03-06"

# ── ROUTING ──
[[routes]]
pattern = "33373984.xyz/*"
zone_name = "33373984.xyz"


# ── OBSERVABILITY ──
[observability]
enabled = false

[observability.logs]
enabled = true
persist = true
invocation_logs = true